# Generated by Django 3.1.6 on 2021-09-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210908_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop.Company', verbose_name='Компания'),
        ),
    ]
