# Generated by Django 3.1.6 on 2021-09-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210914_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ManyToManyField(to='shop.Company', verbose_name='Компания'),
        ),
    ]
