# Generated by Django 3.1.6 on 2021-09-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210915_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='descriptions',
            field=models.CharField(default=1, max_length=250, verbose_name='описание компании'),
            preserve_default=False,
        ),
    ]
