# Generated by Django 3.1.6 on 2021-09-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210915_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзины', 'verbose_name_plural': 'Корзина'},
        ),
    ]
