# Generated by Django 3.2.7 on 2021-09-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210916_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='images/', verbose_name='Картинка категории')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterField(
            model_name='cartcontent',
            name='qty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ManyToManyField(to='shop.Category', verbose_name='Категория товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop.Category', verbose_name='Категория товара'),
        ),
    ]
